Added fix for https://github.com/oxidecomputer/typify/issues/125
oxidecomputer/typify pull request #127
Opened 2022-10-19 22:30 UTC by justinmmott

Further added partialeq trait derive for new types with enums because of the comparison that is done

2022-11-17 19:41 UTC, ahl requested changes

2022-11-17 19:41 UTC, ahl commented on typify-impl/src/value.rs
> +                quote! { #ident ( #inner )}
related to #137, I think that the "path" needs to be a parameter to `output_value` -- simply deleting `super::` will break other cases (that apparently are untested!)

2022-11-17 19:41 UTC, ahl commented on typify-impl/tests/new_type_with_enum.json
> +      "maxLength": 32,
This is a case where I think we should simply ignore `maxLength` or use it to cull the list of value `enum` values.

2022-11-17 19:41 UTC, ahl commented on typify-impl/tests/new_type_with_enum.out
> +pub struct EverythingEnumProperty(EverythingEnumPropertyInner);
I really want `EverythingEnumProperty` in this case to be an `enum`

2022-12-23 01:15 UTC, jayvdb commented
Is this redundant now that https://github.com/oxidecomputer/typify/pull/137 has been merged?

2022-12-27 20:08 UTC, ahl commented
Fixed by #137

2022-12-27 20:08 UTC, closed without merging