make dependency on macros optional
oxidecomputer/typify pull request #213
Opened 2023-03-08 23:25 UTC by jayvdb

c.f. https://github.com/oxidecomputer/progenitor/pull/345

2023-03-08 23:27 UTC, ahl commented
What's the benefit of this? Are you seeing a significantly faster compilation of progenitor without the typify-macro dependency?

2023-03-09 00:03 UTC, jayvdb commented
Main benefit is reduced SBOM/SOUP(Software of Unknown Provenance).  In automotive/medical/etc, every dependency needs to be recorded,audited,etc, so removing unused `typify-macro` and `serde_tokenstream` is a win.

2023-03-09 00:19 UTC, ahl requested changes
ok

2023-03-09 00:19 UTC, ahl commented on typify/Cargo.toml
> +default = ["typify-macro"]
let's call it "macro"

2023-03-09 16:55 UTC, ahl approved these changes

2023-03-09 16:55 UTC, merged